window.ErrorsMes = {
    VALIDATION_ERROR: 'Ошибка валидации',
    INCORRECT_PASSWORD: 'Не верный пароль',
    LOGIN_MUST_BE_UNIQUE: 'Логин должен быть уникальным',
    NOT_ACCESS: 'Нет доступа',
    UNKNOWN_ERROR: 'Неизвестная ошибка',

    NOT_FOUND_REPORT_TYPE: 'Не определен тип отчета',
    NOT_VALID_DATA: 'Данные указаны не верно',
    NO_ACCESS_EDIT_REPORT: 'Вы больше не можете редактировать этот отчет',

    NULL_CONTENT: 'Вы ничего не отправили',
    DELETE_REPORT: 'Отчет уже удален',

    WRONG_DATE: 'Некорректная дата',
    NOT_FOUND_WORKS_ELEMENTS: 'Не получены виды работ',

    FILE_NOT_FOUND: 'Файл не найден',
    REQUEST_IS_EMPTY: 'Запрос пуст',
    INCORRECT_YEAR: 'Некорректный год',
    NOT_FOUND_MKD_CODE: 'Не найден Код МКД',
    NOT_FOUND_WEEKS: 'Не найдены недели',
    NOT_FOUND_WK_CODE: 'Не найдены коды видов работ',
    INCORRECT_MKD_CODE: 'Некорректный Код МКД',
    MANY_FOUND_IMPROG: 'Слишком много работ',
    DUPLICATE_KEY: 'Дубликация ключей',

    ALL_FIELDS_REQUIRED: 'Все поля обязательны для заполнения',

    NOT_FOUND_ADDED_ELEMENTS: 'Не найдены добавляемые элементы',
    WORKKIND_DOES_NOT_EXIST: 'Вид(ы) работ не существует(ют)',
    WK_ID_AND_SUBWORK_NAME_MUST_BE_UNIQUE: 'ID Вида работ и наименование подвида должны быть уникальными',
    NOT_FOUND_UPDATED_ELEMENTS: 'Не найдены обновляемые элементы',
    NOT_FOUND_DELETED_ELEMENTS: 'Не найдены удаляемые элементы',
    NOT_DELETED_BECAUSE_IT_HAS_DEPENDENCIES: 'Нельзя удалить элементы, потому что есть зависимости',

    EMPTY_REQUEST: 'Пустой запрос',
    DIR_CONTAINS_FILES: 'Директория содержит файлы',
    CONTAINS_CHILD_CATALOGS: 'Директория содержит подкаталоги',
    EMPTY_CTG_ID: 'Файл не привязан к каталогу',


    PROBLEM_W_CASE_CREATION: 'Возникла форматирования письма',
    PROBLEM_W_SENDING: 'Ошибка отправки письма',


    BLANK_SKK_ITEM_MUST_BE_UNIQUE: 'Подвиды работ должны быть уникальными',
    WK_DOESNT_MATCH_SKK: 'Вид работ не содержит указанный подвид',
    FAILED_CREATION_SKK_BLANK_ITEM: 'Ошибка при добавлении подвида работ',
    MKD_DOESNT_EXISTS: 'Мкд не существует',
    BLANK_ITEM_MUST_BE_UNIQUE: 'Подвиды работ в графике должны быть уникальными',
    NOT_VALID_NUM_WEEK: 'Не верный номер недели',
    SKK_WEIGHT_MUST_BE_FILLED: 'Веса подвидов работ должны быть заполнены',
    NULL_DATA: 'Нет данных',
    UPDATE_ERROR_SKK: 'Ошибка при изменении подвидов работ',

    ALREADY_EXISTS: 'Уже существует',
    SOMTH_WENT_WRONG_WHEN_DEL_WEEK: 'При удалении недели что-то пошло не так :(',
    EMPTY_AUCTION_CONTROLLED: 'Не найден контролируемый аукцион',
    SELECTED_WEEKS_INCORRECT: 'Не корректно выбраны недели',
    FILES_ADDED: 'Файлы добавлены',
    REPORT_NOT_FILL: 'Отчет не заполнен',
    ALREADY_VIEWED: 'Уже просмотрено',
    CREATED_REPORT_MUST_BE_RBC: 'Создаваемый отчет должен относиться к стройтельному контролю',
    NOT_UPDATED_REPORT: 'Отчет не обновлоен',
    UPDATED_REPORT: 'Отчет обновлен',
    USER_NOT_CURATOR: 'Пользователь не является куратором',
    EMPTY_DATA_RCWCR_BUILD: 'Не удается добавить замечание от стройконтроля',
    EMPTY_DATA_RCWCR_RESPONSE: 'Ответ на замечание не заполнен',
    EMPTY_DATA_RCWCR_CURATOR: 'Не удается добавить замечание от куратора',
    PROBLEM_WITH_CREATE_WEEK_RBC: 'Проблема с зозданием недели стройконтроля',
    PROBLEM_WITH_DELETE_WEEK_RBC: 'Проблема с удалением недели стройконтроля',
    NOT_FOUND_VALID_CONTENT: 'Не корректная информация по выполненым видам работ',
    NOT_FOUND_VALID_CONTENT_EXECUTION: 'Не корректная информация по выполненым подвидам работ',
    NOT_FOUND_RCO_ID: 'Не найден идентификатор еженедельного отчета подрядчика',
    NOT_FOUND_RCWCR_ID: 'Не найдено замечание, на которое требуется ответить',
    UNIQUE_DATA_ERROR: 'Данные должны быть уникальными',
    CHECK_FILL_DATA_IN_RCWCR: 'Не заполнено замечание',
    ERROR_RECEIVING_RBC: 'Ошибка получения отчета стройконтроля',
    ERROR_RECEIVING_OLD_RBC: 'Ошибка получения СТАРОГО отчета стройконтроля',
    ERROR_RECEIVING_RCO: 'Ошибка получения отчета подрядчика',
    ERROR_RECEIVING_OLD_RCO: 'Ошибка получения СТАРОГО отчета подрядчика',
}
